[project]
name = "project-1-otsu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imageio>=2.37.0",
    "marimo>=0.11.7",
    "matplotlib>=3.10.1",
    "numpy>=2.2.3",
    "scikit-image>=0.25.2",
]
